version: '3.3'
services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - ./db/migrations/:/docker-entrypoint-initdb.d/:consistent
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'pass'
      POSTGRES_DB: 'devices'
    ports:
      - 6432:5432

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    ports:
      - 5672:5672
      - 15672:15672

volumes:
  pg-data:
